/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_13_Jubilee_Road_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_13_Jubilee_Road_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_3_Jubilee_Road_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_3_Jubilee_Road_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_5_Jubilee_Road_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_5_Jubilee_Road_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_9_Jubilee_Road_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_9_Jubilee_Road_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Campus_Lodge_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Campus_Lodge_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_College_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_College_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bernard_Price_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bernard_Price_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bernard_Price_Sub_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bernard_Price_Sub_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bidvest_Stadium_Lighting_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bidvest_Stadium_Lighting_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bidvest_Stadium_Pavillion_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bidvest_Stadium_Pavillion_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Biology_Building_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Biology_Building_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Biology_Building_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Biology_Building_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_B_C_Sports_Field_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_B_C_Sports_Field_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Cricket_A_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Cricket_A_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Main_Incomer_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Main_Incomer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Rugby_Stadium_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Bozzoli_Rugby_Stadium_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Cafe_Fino_Origins_Center_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Cafe_Fino_Origins_Center_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Central_Block_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Central_Block_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Central_Block_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Central_Block_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_4_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Compound_Sub_Trf_4_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Digital_Arts_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Digital_Arts_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Emthonjeni_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Emthonjeni_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_HT_Meter_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_HT_Meter_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_TRF_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Gatehouse_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Groundsman_Cottage_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Groundsman_Cottage_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hillman_Building_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hillman_Building_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hillman_Building_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hillman_Building_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hofmeyer_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Hofmeyer_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_International_House_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_International_House_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_International_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_International_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Ithemba_Labs_GEN_KVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Ithemba_Labs_GEN_KVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Ithemba_Labs_Submersible_Pumps_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Ithemba_Labs_Submersible_Pumps_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jan_Smuts_House_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jan_Smuts_House_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jan_Smuts_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jan_Smuts_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_John_Moffat_Sub_Trf_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Dining_Hall_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Dining_Hall_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Dining_Hall_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Dining_Hall_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Generator_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Generator_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_Lifts_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_Lifts_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_Residence_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_Residence_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Jubilee_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Main_Dining_Hall_Matrix_GEN_250_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Main_Dining_Hall_Matrix_GEN_250_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matric_PPS_for_Professionals_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ABSA_Bank_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ABSA_Bank_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Basement_DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Basement_DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Butchers_Grill_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Butchers_Grill_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Capitec_Bank_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Capitec_Bank_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Chinese_Lantern_Takeaways_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Chinese_Lantern_Takeaways_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Chinese_Lantern_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Chinese_Lantern_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Computers__kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Computers_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Cross_Roads_Driving_School_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Cross_Roads_Driving_School_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_DJ_Sports_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_DJ_Sports_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Debonairs_1_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Debonairs_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Debonairs_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Debonairs_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Delhi_Delicious_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Delhi_Delicious_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Deli_Delicious_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Deli_Delicious_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_FUNDI_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_FUNDI_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_First_National_Bank_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_First_National_Bank_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Fresher_Breath_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Fresher_Breath_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Jetline_com_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Jetline_com_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Just_Taste_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Just_Taste_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Kara_Nichha_s_kVar
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Kara_Nichha_s_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Dining_Hall_East_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Dining_Hall_East_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Dining_Hall_West_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Dining_Hall_West_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Incomer__kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Main_Incomer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Nedbank_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Nedbank_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Ninos_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Ninos_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Optometrist_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Optometrist_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_PPS_for_Professionals_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Panel_D9_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Panel_D9_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Pentz_Book_Shop_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Pentz_Book_Shop_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Pentz_Book_Shop_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Pentz_Book_Shop_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_SBM_G_Panel_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_SBM_G_Panel_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_SMB_G_Ground_Floor_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_SMB_G_Ground_Floor_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Sausage_Saloon_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Sausage_Saloon_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Sizzlers_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Sizzlers_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Standard_Bank_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Standard_Bank_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Stationery_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Stationery_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ISTpassword_Corner_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ISTpassword_Corner_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_The_Sweets_Park_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_The_Sweets_Park_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Van_Schaik_Bookstore_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_Van_Schaik_Bookstore_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ZA_Cellular_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Matrix_ZA_Cellular_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Commerce_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Commerce_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Dalrymple_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Dalrymple_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_John_Moffat_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_John_Moffat_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Sunnyside_Residence_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_New_Sunnyside_Residence_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_North_West_Engineering_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_OLS_Building_GEN_65_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_OLS_Building_GEN_65_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_OLS_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_OLS_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Dalrymple_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Dalrymple_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Dental_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Dental_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Mutual_Sports_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Mutual_Sports_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Sunnyside_Residence_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Old_Sunnyside_Residence_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Origin_Centre_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Origin_Centre_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Origins_Centre_GEN_220_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Origins_Centre_GEN_220_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PDH_Mini_Sub_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PDH_Mini_Sub_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PDH_Zesti_Lemon_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PDH_Zesti_Lemon_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PDH___water_meter_kl
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PG_Club_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_PG_Club_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Physics_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Physics_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_Borehole_Pump__38146549__kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_Borehole_Pump__38146549__kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_Sub_Total__38146548__kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_Sub_Total__38146548__kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Planetarium_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_GEN_800_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_GEN_800_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_2_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_3_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_4_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Solomon_Mahlangu_House_TRF_4_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Swimming_Bath_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Swimming_Bath_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Swimming_Pool_HP_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Swimming_Pool_HP_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Theatre_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Theatre_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Theo_Senate_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Theo_Senate_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Umthombo_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Umthombo_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Van_Riet_Louw_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Van_Riet_Louw_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Wartenweiler_Library_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_Wartenweiler_Library_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_William_Cullen_Library_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_EC_William_Cullen_Library_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Mortuary_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Mortuary_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Essellen_Street_TRF3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Choir_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Choir_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Indian_Studies_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Indian_Studies_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Vodacom_Tower_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_Vodacom_Tower_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Graduate_Lodge_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_IBM_Tshimologong_Building_Enermax_Q1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_IBM_Tshimologong_Building_Enermax_Q4_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_IBM_Tshimologong_Building_Enermax_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_High_Voltage_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_High_Voltage_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_Nutron_Source_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_Nutron_Source_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_TRF_A_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_TRF_A_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_TRF_B_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Ithemba_Labs_TRF_B_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Block_H_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Block_H_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Boiler_Room_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Boiler_Room_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Dining_Hall_GEN_125_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Dining_Hall_GEN_125_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Dinning_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Dinning_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Leighton_North_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Leighton_North_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Leighton_South_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Leighton_South_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Main_Sub_Hostel_1_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Main_Sub_Hostel_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Main_Sub_Kiosk_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Main_Sub_Kiosk_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Northwards_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Northwards_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Williams_Hall_1_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Knockando_Williams_Hall_1_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_HT_Meter_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_HT_Meter_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Medical_School_Transformer_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Conacher_Block_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Conacher_Block_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Conacher_Block_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Conacher_Block_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Harald_Holmes_Library_TRF_1_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Harald_Holmes_Library_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Harald_Holmes_Library_TRF_2_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Harald_Holmes_Library_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_Dining_Hall_GEN_150_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_Dining_Hall_GEN_150_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_Dinning_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_Dinning_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Highfield_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Lesideng_Extention_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Lesideng_Extention_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_GEN_400_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_GEN_400_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Linder_Auditorium_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Marang_Block_Trf_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Marang_Block_Trf_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Marang_Block_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Marang_Block_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Matrons_Blocks_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Matrons_Blocks_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Medhurst_Residence_GEN_650_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Medhurst_Residence_GEN_650_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_PIMD_Office_Block_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_PIMD_Office_Block_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Physical_Education_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Physical_Education_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Girton_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Girton_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Medhurst_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Medhurst_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Reith_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Residence_Reith_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_School_of_Public_Health_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_School_of_Public_Health_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Siyafunda_Cafe_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Siyafunda_Cafe_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Stadium_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Stadium_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Wozani_Block_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_PEC_Wozani_Block_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Philip_V_Tobias_Main_Incomer_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Philip_V_Tobias_Main_Incomer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_2__38111362__kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_2__38111362__kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Admin_Block_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Duro_Plastics_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Duro_Plastics_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Struct_Crete_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Struct_Crete_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Science_Park_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_South_Court_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_South_Court_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_HT_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_HT_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_1_Kiosk_Shosholoza_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_1_Kiosk_Shosholoza_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Kum_Saan_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Kum_Saan_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Ntombela_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Ntombela_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Parna_Janda_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_2_Kiosk_Parna_Janda_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Amagumbi_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Amagumbi_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Emakhaya_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Emakhaya_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Mohokare_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Mohokare_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Sarie_Marais_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_3_Kiosk_Sarie_Marais_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Amawasha_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Amawasha_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Great_Heart_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Great_Heart_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Languta_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_4_Kiosk_Languta_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_Egoli_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_Egoli_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_LS1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_LS1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_LS2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_5_Kiosk_LS2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Ingolovane_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Ingolovane_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Mbube_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Mbube_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Parkade_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Parkade_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Stimela_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS_6_Kiosk_Stimela_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___001_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___001_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___002_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___002_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___003_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___003_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___004_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___004_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___005_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___005_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___006_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_MSS___006_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_ePitstop_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_The_Junction_ePitstop_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Catering_DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Catering_DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Club_DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Club_DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Founders_Square_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Founders_Square_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Generator_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Generator_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_IBM_DB_ION_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_IBM_DB_ION_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_JCE_DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_JCE_DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_LV_Total_Q1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_LV_Total_Q4_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_LV_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Main_Incomer_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Main_Incomer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Makers_Lab_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Makers_Lab_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Restaurant_DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_Restaurant_DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_TP___DB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_Tshimologong_Building_TP___DB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_University_Corner_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_University_Corner_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Albert_Wessels_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Albert_Wessels_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Albert_Wessels_GEN_300_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Albert_Wessels_GEN_300_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Donald_Gordon_GEN_350_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Donald_Gordon_GEN_350_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Donald_Gordon_Sub_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Donald_Gordon_Sub_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Kitchen_GEN_125_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Kitchen_GEN_125_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Kitchen_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Kitchen_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Residence_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Residence_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Residence_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_EOH_Residence_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Faculty_Office_M_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Faculty_Office_M_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_C_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_C_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_F_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_F_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_H_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_H_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_J_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_J_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_K_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_K_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_L_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_L_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_Q_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_Q_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_S_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_S_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_U_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_House_U_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Mwalimu_House_GEN_125_kVA_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Mwalimu_House_GEN_125_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Mwalimu_House_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Mwalimu_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_North_Lodge_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_North_Lodge_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Parktown_Village_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Parktown_Village_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Sarua_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Sarua_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_House_1___7_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_House_1___7_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_4___7_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_4___7_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_8___11_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_8___11_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_Minisub_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WBS_Trematon_Place_Minisub_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_Residence_A___D_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_Residence_A___D_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Barnato_Sub_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_Building_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_Building_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_Building_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_Building_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_GEN_275_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLM_GEN_275_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLTD_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_CLTD_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Catering_Mayas_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Catering_Mayas_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Chamber_of_Mines_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Chamber_of_Mines_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Chamber_of_Mines_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Chamber_of_Mines_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Claude_Vergie_House_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Claude_Vergie_House_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Club_Minisub_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Club_Minisub_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Convocation_Dining_Hall_GEN_125_kVa_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Convocation_Dining_Hall_GEN_125_kVa_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Convocation_Kitchen_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Convocation_Kitchen_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_DJ_du_Plessis_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_DJ_du_Plessis_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_David_Webster_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_David_Webster_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Dig_Fields_Rugby_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Dig_Fields_Rugby_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Dig_Fields_Soccer_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Dig_Fields_Soccer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_East_Avenue_Mini_Sub_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_East_Avenue_Mini_Sub_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_3_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_3_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_4_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Educom_Building_Trf_4_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_FNB_Building_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_FNB_Building_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_FNB_Building_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_FNB_Building_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Flower_Hall_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Flower_Hall_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_LAB_HT_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_LAB_HT_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_LAB_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_LAB_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_Sub_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Genmin_Sub_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Gymnasium_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Gymnasium_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29A_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29A_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29B_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29B_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29C_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Hall_29C_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Humphrey_Raikes_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Humphrey_Raikes_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_Building_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_Building_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_North_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_North_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_South_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Maths_Science_South_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Old_Grandstand_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Old_Grandstand_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Oliver_Schreiner_School_of_Law_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Oliver_Schreiner_School_of_Law_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Supply_No_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Supply_No_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Supply_No_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Supply_No_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Wash_Bay_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_PIMD_Wash_Bay_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Raikes_Road_Main_Incomer_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Raikes_Road_Main_Incomer_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Science_Stadium_TRF_1_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Science_Stadium_TRF_1_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Science_Stadium_TRF_2_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Science_Stadium_TRF_2_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Squash_Courts_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Squash_Courts_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_A_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_A_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_B_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_B_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_C_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_C_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_D_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_D_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_E_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_E_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_F_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_F_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_G_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_G_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_H_kVArh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Stdnts_Village_Unit_H_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Kitchen_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Kitchen_kVarh_exp
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Kitchen_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Kitchen_kWh_exp
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Park_GEN_300_kVA_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Park_GEN_300_kVA_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Park_Main_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Sturrock_Park_Main_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_The_Barns_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_The_Barns_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Tower_of_Lights_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Tower_of_Lights_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Village_Minisub_Total_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Village_Minisub_Total_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Village_Zesti_Lemonz_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_Village_Zesti_Lemonz_kWh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_CLUB_GENERATOR_100_kVa_kVarh
/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_WC_/usr/share/opentsdb/bin/tsdb uid delete metrics WITS_CLUB_GENERATOR_100_kVa_kWh